apiVersion: v1
kind: Service
metadata:
  name: middleware-service
  namespace: microgrid
spec:
  type: NodePort
  selector:
    app: middleware-service
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800              # ✅ External access via minikube
